### PR TITLE
fix: ignore invalid filter id

### LINKED ISSUE #2356: SVGs with filters not displayed in v15.4.0 on iOS
### Description

When displaying an SVG that contains a filter, the svg is not displayed when using v15.4.0. It works fine in v15.3.0. The issue only occurs on iOS, Android is fine.

### Steps to reproduce

Add the following code/files:

App.ts:

```
import React from 'react';
import {SafeAreaView, Text} from 'react-native';
import SvgNoFilter from './user-location-dot-no-filter.svg';
import SvgFilter from './user-location-dot.svg';

function App(): React.JSX.Element {
  return (
    <SafeAreaView>
      <Text>SVG without filter</Text>
      <SvgNoFilter />
      <Text>SVG with filter</Text>
      <SvgFilter />
    </SafeAreaView>
  );
}

export default App;
```
user-location-dot-no-filter.svg:

```
<svg width="30" height="31" viewBox="0 0 30 31" fill="none" xmlns="http://www.w3.org/2000/svg">
    <g >
        <circle cx="15" cy="14" r="12" fill="white"/>
        <circle cx="15" cy="14" r="8" fill="#1770E5"/>
    </g>
</svg>
```

user-location-dot.svg:

```
<svg width="30" height="31" viewBox="0 0 30 31" fill="none" xmlns="http://www.w3.org/2000/svg">
    <g filter="url(#filter0_dd_5170_65449)">
        <circle cx="15" cy="14" r="12" fill="white"/>
        <circle cx="15" cy="14" r="8" fill="#1770E5"/>
    </g>
    <defs>
        <filter id="filter0_dd_5170_65449" x="0.5" y="0" width="29" height="30.5" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
            <feFlood flood-opacity="0" result="BackgroundImageFix"/>
            <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha"/>
            <feOffset dy="2"/>
            <feGaussianBlur stdDeviation="1.25"/>
            <feComposite in2="hardAlpha" operator="out"/>
            <feColorMatrix type="matrix" values="0 0 0 0 0.301961 0 0 0 0 0.403922 0 0 0 0 0.682353 0 0 0 0.17 0"/>
            <feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_5170_65449"/>
            <feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha"/>
            <feOffset/>
            <feGaussianBlur stdDeviation="1"/>
            <feComposite in2="hardAlpha" operator="out"/>
            <feColorMatrix type="matrix" values="0 0 0 0 0.243137 0 0 0 0 0.247059 0 0 0 0 0.258824 0 0 0 0.08 0"/>
            <feBlend mode="normal" in2="effect1_dropShadow_5170_65449" result="effect2_dropShadow_5170_65449"/>
            <feBlend mode="normal" in="SourceGraphic" in2="effect2_dropShadow_5170_65449" result="shape"/>
        </filter>
    </defs>
</svg>

```

Result: 
image

Now revert back to v15.3.0:

```
npm i react-native-svg@15.3.0
cd ios && pod install && cd ..     
```

Result:
image

### Snack or a link to a repository

https://github.com/fikkatra/react-native-svg-with-filters

### SVG version

15.4.0

### React Native version

0.74.3

### Platforms

iOS

### JavaScript runtime

None

### Workflow

React Native

### Architecture

None

### Build type

Debug app & dev bundle

### Device

iOS simulator

### Device model

iPhone 15 Pro, iOS 17.5

### Acknowledgements

Yes

### PR DESCRIPTION
**Pull request by jakex7**
# Summary

Closes #2356
Currently, when `filter` prop is defined, but there is no equivalent `<Filter>` component, on iOS nothing is rendered, with this fix this prop would be ignored, and the component should render as expected.

## Test Plan

```tsx
<Svg width="400" height="400" viewBox="0 0 124 124" fill="none">
  <Rect width="124" height="124" rx="24" fill="red" filter="url(#nonExistingFilterId)"/>
</Svg>
```

## Affected platforms

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |

### CODE REVIEW

File: apple/RNSVGRenderable.mm [hunk 1]
```diff
@@ -250,7 +250,10 @@ - (void)renderTo:(CGContextRef)context rect:(CGRect)rect
 
   [self beginTransparencyLayer:context];
 
-  if (self.mask || self.filter) {
+  RNSVGFilter *filterNode = self.filter ? (RNSVGFilter *)[self.svgView getDefinedFilter:self.filter] : nil;
+  RNSVGMask *maskNode = self.mask ? (RNSVGMask *)[self.svgView getDefinedMask:self.mask] : nil;
+
+  if (maskNode || filterNode) {
```
Comment (WoLewicki) [inline apple/RNSVGRenderable.mm:256]: What was the flow for mask? Was it not working too before? If so, check if there are no issues regarding it that we could close with this PR.

File: apple/RNSVGRenderable.mm [hunk 2]
```diff
@@ -250,7 +250,10 @@ - (void)renderTo:(CGContextRef)context rect:(CGRect)rect
 
   [self beginTransparencyLayer:context];
 
-  if (self.mask || self.filter) {
+  RNSVGFilter *filterNode = self.filter ? (RNSVGFilter *)[self.svgView getDefinedFilter:self.filter] : nil;
```
Comment (WoLewicki) [inline apple/RNSVGRenderable.mm:253]: Why do we need casts here? Shouldn't the method return type be `RNSVGFilter`?

Comment (jakex7) [reply apple/RNSVGRenderable.mm]: Fixed in [ea60684](https://github.com/software-mansion/react-native-svg/pull/2360/commits/ea60684b087e54a4541d1c550f371f77de6abe02)
