### PR TITLE
fix: implementation toDataURL for iOS platform both architectures

### LINKED ISSUE #2233: toDataURL only works the second time it is executed in old Arch
Hello,

in iOS and old Arch, I found that the callback on toDataURL method will only be called the second time of asking. This is due to when the queue from UIManager in iOS is flushed. See https://github.com/facebook/react-native/issues/1365 

I traced the problem to the iOS implementation and will do a PR with my fix.

## Environment info

React native info output:

```bash
System:
  OS: macOS 14.3.1
  CPU: (12) arm64 Apple M2 Max
  Memory: 96.39 MB / 32.00 GB
  Shell:
    version: 3.6.0
    path: /opt/homebrew/bin/fish
Binaries:
  Node:
    version: 18.19.1
    path: ~/.nvm/versions/node/v18.19.1/bin/node
  Yarn:
    version: 1.22.21
    path: ~/.nvm/versions/node/v18.19.1/bin/yarn
  npm:
    version: 10.2.4
    path: ~/.nvm/versions/node/v18.19.1/bin/npm
  Watchman:
    version: 2024.01.22.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11330709
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.4
    wanted: 0.73.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

Library version: 14.1.0

## Steps To Reproduce

Simply run the Examples App in this repo with `react-native 0.73.4` and go to "Tap the shapes to render the Image below based on the base64-data of the Svg". If you click once, nothing happens, but if you click a second time, the image is rendered.

### PR DESCRIPTION
**Pull request by bohdanprog**
# Summary
Closes #2233 
in iOS and old Arch, a callback on `toDataURL` method will only be called the second time of asking. 
Based on that [PR](https://github.com/software-mansion/react-native-svg/pull/2234)
format `RNSVGSvgViewModule` file.

## Test Plan
We can easily test that fix by running the `Test2233`, we have an example of the problem.

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅      |

### CODE REVIEW

File: apple/RNSVGSvgViewModule.mm [hunk 1]
```diff
@@ -91,4 +84,13 @@ - (void)toDataURL:(nonnull NSNumber *)reactTag
...
+- (dispatch_queue_t)methodQueue
+{
+  if (self.bridge) {
+    return RCTGetUIManagerQueue();
+  } else {
+    return dispatch_get_main_queue();
+  }
+}
+
+@end
```
Comment (jakex7) [inline apple/RNSVGSvgViewModule.mm:96]: New line

**Review by jakex7 — APPROVED** [review]
Left one comment, other than that LGTM
