### PR TITLE
Fix #1345: opacity does not work with currentColor on Android

### LINKED ISSUE #1345: On the Android platform, when using currentColor as the fill value, the opacity property is ignored.
#### Unexpected behavior

On the Android platform, when using currentColor as the fill value, the opacity property is ignored. The iOS platform has no such problems

Simulator Screen Shot - iPhone 11 - 2020-04-14 at 14 02 29
Screenshot_1586844684

## Environment info

```bash
 "react-native-svg": "^12.1.0",
```

## Steps To Reproduce
```javascript

 let xml = `<?xml version="1.0" encoding="utf-8"?>
  <svg version="1.1" id="e98f3141-fbb2-4194-a12f-8ac40d4ee285"
     xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 200 200"
     style="enable-background:new 0 0 200 200;" xml:space="preserve">
  <title>listen_now_inactive</title>
  <path fill="currentColor" d="M85.3,24.3h-59c-6.2,0-11.3,5-11.3,11.1c0,0.1,0,0.1,0,0.2v8.7h92.8l-8.3-12.5C96.2,27.2,90.9,24.4,85.3,24.3z"
    />
  <g>
    <path fill="currentColor" opacity="0.1" d="M173.7,44.3H15v119c0,0.1,0,0.1,0,0.2c0,6.2,5.1,11.2,11.3,11.1h147.4c0.1,0,0.1,0,0.2,0
      c6.2,0,11.2-5.1,11.1-11.3V55.6c0-0.1,0-0.1,0-0.2C185,49.3,179.9,44.3,173.7,44.3z M127.6,114.1l-47.3,20.8
      c-0.6,0.3-1.3,0.4-2,0.4c-2.8,0-5.1-2.3-5.1-5.1V88.7c0-0.7,0.1-1.4,0.4-2c1.1-2.6,4.1-3.7,6.7-2.6l47.3,20.8
      c1.3,0.5,2.2,1.5,2.8,2.7C131.5,110.1,130.2,113,127.6,114.1z"/>
    <path fill="currentColor" d="M127.6,104.8L80.3,84c-2.6-1.1-5.5,0-6.7,2.6c-0.3,0.6-0.4,1.3-0.4,2v41.5c0,2.8,2.3,5.1,5.1,5.1
      c0.7,0,1.4-0.1,2-0.4l47.3-20.8c2.6-1.1,3.8-4,2.8-6.6C129.9,106.2,128.9,105.3,127.6,104.8z"/>
  </g>
  </svg>`;

 <SvgCss xml={xml} width="100" height="100" color="red" />

```

Describe what you expected to happen:
 The renderings of iOS and Android platforms should look the same

### PR DESCRIPTION
**Pull request by laptou**
# Summary

Fixes #1345.

On Android, the `opacity` property was ignored while rendering if the fill / stroke was set using `currentColor`. 

Incorrect (the top left square should be translucent, because it has `fill="currentColor"` and `opacity={0.2}`):
Screenshot_20230702_171928_TestsExample

Fixed:
Screenshot_20230702_171803_TestsExample

I implemented this by multiplying the alpha of the `currentColor` by the opacity when setting a `currentColor` brush.

### What's required for testing (prerequisites)?

- `yarn` in repo root
- `yarn` in `TestsExample` folder

### What are the steps to reproduce (after prerequisites)?

- Run the `TestsExample` app and edit its `App.js` to show `Test9999`

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ❌     |
| Android |    ✅     |

## Checklist

- [x] I have tested this on a device and a simulator
- [ ] I added documentation in `README.md`
- [ ] I updated the typed files (typescript)
- [ ] I added a test for the API in the `__tests__` folder

### CODE REVIEW

File: TestsExample/App.js [hunk 1]
```diff
@@ -6,8 +6,9 @@ import Test1374 from './src/Test1374';
 import Test1718 from './src/Test1718';
 import Test1813 from './src/Test1813';
 import Test1845 from './src/Test1845';
+import Test2080 from './src/Test2080';
 import PointerEventsBoxNone from './src/PointerEventsBoxNone';
 
 export default function App() {
-  return <ColorTest />;
+  return <Test2080 />;
```
Comment (WoLewicki) [inline TestsExample/App.js:13]: We don't want to change the default test here.

```suggestion
  return <ColorTest />;
```

**Review by WoLewicki — APPROVED** [review]
LGTM! Thanks for your contribution :rocket:
